# .goreleaser.yaml
version: 2
project_name: agent-team

builds:
  - binary: agent-team
    ldflags:
      - -s -w
      - -X github.com/JsonLee12138/agent-team/cmd.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: JsonLee12138
      name: homebrew-agent-team
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/JsonLee12138/agent-team
    description: AI team role manager — git worktrees + terminal multiplexer
    install: |
      bin.install "agent-team"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
